# Generated by Django 5.2.8 on 2025-11-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('analise', models.CharField(blank=True, max_length=50, null=True)),
                ('certidao', models.CharField(blank=True, max_length=50, null=True)),
                ('redacao', models.CharField(blank=True, max_length=50, null=True)),
                ('teste_sondagem', models.CharField(blank=True, max_length=255, null=True)),
                ('prova_matematica', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
    ]
