# Generated by Django 5.2.7 on 2025-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
