# Generated by Django 5.2.7 on 2025-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_candidato_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=155, null=True),
        ),
    ]
